# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.
"https://search.{default}/":
    type: upstream
    upstream: "search:http"
    cache:
      enabled: false